Enable editable scenarios
sotopia-lab/sotopia-demo pull request #7
Opened 2024-08-13 19:14 UTC by bugsz

The same as #6, but in a new branch name.
The first commit addresses #3, and the following commits address #4 

Btw whether the scenario is editable does not relate to the omniscient? (i.e. we can still only show partial information while making the scenario editable?)

2024-08-13 20:02 UTC, XuhuiZhou commented
Good point! This is just a feature that I am suggesting. Cuz once people want to edit things, that usually implies they want full control. This is basically making things easier to handle.

2024-08-13 20:19 UTC, XuhuiZhou requested changes
![image](https://github.com/user-attachments/assets/7137f060-0a0e-49ea-bc2b-213390af9b3d)
Some meta-comments:
* Instead of listing the "create your own scenario" on the side bar. Create a button on the above to with text like "editable", once it is selected, all the things become editable and goals become omniscient
* Put scenario in a single row, besides just listing the codename, include a few tokens of the scenario, so people could have a preview of the scenario before choing them
* Allow choose models for each agent, include a special human model, which would require human input. If all models are not humans, then we do normal sotopia simulation.

2024-08-14 20:05 UTC, XuhuiZhou commented
@bugsz thanks for the update, some new feedback
![Screenshot 2024-08-14 at 12 14 49 PM](https://github.com/user-attachments/assets/2b031e08-f51d-4561-a72b-dc154660a13f)

2024-08-15 03:36 UTC, bugsz commented
Still in progress..
Currently support the flexible choice of agents (including human-human and model-model interaction)

2024-08-16 20:27 UTC, bugsz commented
A bit strange behavior on my end:
Now I can edit the scenario and agent bg. I can see the change reflected in the environment (and also in LLMAgent.inbox). But I did not see the conversation change as expected (for example, I make one agent to be `giselle does not want to talk` but the conversation is still long. @XuhuiZhou Is it possible for you to see what's happening?

2024-08-16 20:31 UTC, XuhuiZhou commented
> A bit strange behavior on my end: Now I can edit the scenario and agent bg. I can see the change reflected in the environment (and also in LLMAgent.inbox). But I did not see the conversation change as expected (for example, I make one agent to be `giselle does not want to talk` but the conversation is still long. @XuhuiZhou Is it possible for you to see what's happening?
Try debugging by outputting the agent prompt?

2024-08-20 19:56 UTC, XuhuiZhou approved these changes
Thanks for the efforts, I left some comments but for the sake of moving fast. I will let you decide what to merge.

2024-08-20 19:56 UTC, XuhuiZhou commented on socialstream/chat/callbacks.py
> +from sotopia.database import EpisodeLog
move this to the top

2024-08-20 19:56 UTC, XuhuiZhou commented on socialstream/chat/callbacks.py
> +    from socialstream.rendering_utils import render_messages
move this?

2024-08-20 19:56 UTC, XuhuiZhou commented on socialstream/chat/callbacks.py
> +    # print(epilog.render_for_humans())
remove this

2024-08-20 19:56 UTC, XuhuiZhou commented on socialstream/rendering_utils.py
> +def _agent_profile_to_friendabove_self(
why we are re-writing this?

2024-08-20 19:56 UTC, XuhuiZhou commented on socialstream/rendering_utils.py
> +def render_messages(
shouldn't this be in the rendering folder?

2024-08-20 19:56 UTC, XuhuiZhou commented on socialstream/chat/chat_omniscient.py
qq, isn't chat_omniscient kind of replicating a lot of features in chat.py? Can we combine them?

2024-08-20 19:57 UTC, XuhuiZhou commented
Also, I notice that we use the callback functions. Any chance you can update the readme to introduce/explain that concept?

2024-08-20 20:27 UTC, bugsz commented
@XuhuiZhou I think ready to merge!

2024-08-20 20:31 UTC, merged